id: P007016
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD19458
  title: 'སྐྱབས་རྗེ ༧་ཀརྨ་སྟོབས་རྒྱལ་རིན་པོ་ཆེའི་བཀའ་འབུམ། '
  author: ''
  volumes:
    bb72cf5e41ee46af8f5fd128f71346ff:
      image_group_id: I2PD19462
      title: ''
      volume_number: 1
      total_pages: 466
    79e493f14df34a59a3aed984129f03c1:
      image_group_id: I2PD19463
      title: ''
      volume_number: 2
      total_pages: 462
    38ee26c6f3a14772b9d908784af4c77d:
      image_group_id: I2PD19464
      title: ''
      volume_number: 3
      total_pages: 388
ebook_metadata:
  title: 'སྐྱབས་རྗེ ༧་ཀརྨ་སྟོབས་རྒྱལ་རིན་པོ་ཆེའི་བཀའ་འབུམ། '
  author: ''
  sku: P007016
  cover: cover.jpg
  layers:
  - pagination
