id: I937AAC7F
legacy_id: P007016
ocr_import_info:
  bdrc_scan_id: W2PD19458
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T21:18:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:40:44.871232+00:00'
last_modified: 2022-09-03 18:41:14.790213
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19458
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19458
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྐྱབས་རྗེ ༧་ཀརྨ་སྟོབས་རྒྱལ་རིན་པོ་ཆེའི་བཀའ་འབུམ།
  author: ཀརྨ་སྟོབས་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.9122389926128861
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD19463:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19463
      total_pages: 462
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD19463.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9025308495780734
    legacy_id: v002
  I2PD19464:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19464
      total_pages: 388
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD19464.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9232443252401109
    legacy_id: v003
  I2PD19462:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD19462
      total_pages: 466
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD19462.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9127671243506195
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
